name: Release

on:
  push:

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            image: quay.io/pypa/manylinux_2_34_x86_64
            TARGET: Linux
            PYINSTALLER_ARGS: >-
              --onefile
              --add-data 'src/usdb_syncer/db/sql:src/usdb_syncer/db/sql'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Set up Python
        run: |
          ln -sf /opt/python/cp312-cp312/bin/python3 /usr/bin/python3
          ln -sf /opt/python/cp312-cp312/bin/pip3 /usr/bin/pip3
          ln -sf /opt/python/cp312-cp312/bin/python3 /usr/bin/python
          ln -sf /opt/python/cp312-cp312/bin/pip3 /usr/bin/pip
      - name: Install poetry
        run: |
          python -m pip install poetry
          ln -sf /opt/python/cp312-cp312/bin/poetry /usr/bin/poetry
      - name: Install dependencies
        run: |
          poetry install --without dev
      - name: Write version and commit hash
        run: >
          poetry run write_release_info
          -p src/usdb_syncer/constants.py
          -v ${{ github.ref_name }}
          -c ${{ github.workflow_sha }}
      - name: Generate GUI elements
        run: poetry run generate_pyside_files
      - name: Build with pyinstaller for ${{matrix.os}}
        # _tkinter hook is run erroneously?
        run: >
          poetry run pyinstaller
          -n 'USDB_Syncer-${{github.ref_name}}-${{matrix.TARGET}}'
          --exclude-module _tkinter
          ${{matrix.PYINSTALLER_ARGS}}
          src/usdb_syncer/gui/__init__.py
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*Linux
